<template>
  <div class="ChatSide">
    <search-panel></search-panel>
    <div class="receiveList star-side-main">
      <vue-scroll :ops='ops'>
        <receive-item v-for="(item,index) in receiveList" :key="index" :item='item'></receive-item>
      </vue-scroll>
    </div>
  </div>
</template>
<script>
import SearchPanel from "@components/SearchPanel"
import ReceiveItem from "@components/ReceiveItem"
export default {
  data(){
    return{
      search:'',
      receiveList:[
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },{
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },
        {
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        },{
          name:"冯倩",
          avatar:'',
          desc:'',
          time:'14：06'
        },
         {
          name:"订阅号",
          avatar:'',
          desc:'前端大全，做了八年前端还是一事无成',
          time:'昨天'
        }
      ],
      ops:{
        bar:{
          background:'#e8e6e6'
        }
      }
    }
  },
  components:{
    SearchPanel,
    ReceiveItem
  }
}
</script>
<style lang="scss" scoped>
.ChatSide{
  width: 315px;
  background-color: #f5f5f5;
  display: flex;
  flex-direction: column;
  border-right: 1px solid #DCDFE6;
}
</style>
